CLUSTAL multiple sequence alignment by MUSCLE (3.8)


AGE11890.1                          ---SGGHRPGPPGPTEPG-----------GQARGRQRPAADAERRGPR--RSGAAGTLRG
WP_015217392.1                      ------MVAELKTEIKYH-----------ETFIPGQREPILVLRNLL---EAGIFANYVM
tr|U2JZQ2|U2JZQ2_9FIRM              -MDNMLFFQKLENYKEYI-----------IDTLERNLDKYIVTVNIVKSFLKQHNDSYII
AAS61889.1                          -----------MKISEFL-----------HLALPEEQWLPTISGVL----RQFAEEECYV
WP_054452513.1                      ---------MKTNFSNEG-----------TTQSDEQNLIFARAAALA---DSGIFKEYLI
tr|F6CXE6|F6CXE6_MARPP              MHPIELTLKCLPDSRDGVLNMSNIALDLNITSSNTKNDVFELAARLA---SSKLFEDYMI
tr|H6R5M0|H6R5M0_NOCCG              -----MNRPTTLDADGYV-----------HSTRPHTGDPLALATAIA---ASSQLTDFAV
tr|A0A426PWW0|A0A426PWW0_9CORY      ------MRHHGIGRHGGV--------------------------------DTGVG-----
CCP45174.1                          --MSELSVATGAVSTASS-----------SIPMPAGVNPADLAAELAAVVTESVDEDYLL
AMK48233.1                          -------------MLRYL---------SAETELPADGDPLLLVAKLA---ESGLFDQYVV
WP_009076320.1                      ------MGPGVRGEGAGM-----------TVRVSRQTEPLQQMTALA---RAG-YDDYVV
BAD55464.1                          -----MSTTDERSRVEYV------------------TDPAAAMSRLA---SADRFGEYVM
WP_011146566.1                      -------AEHGRPMQQYH-----------EQTVVITSTPLDLITHLL---SEGEAQPYML
AKQ52535.1                          --------MAKPTFTQYH-----------THTITHQCDPQTLATALS---GAEFCHDYVV
                                                                                                

AGE11890.1                          RPRRRGGRHAAGGRGHRGARRRCLPRVRRHRRGRDPRRKPDQ-GDPLPRRSGYLSHRPAR
WP_015217392.1                      YE--GNNEVRIAG-NELVRVSVSQDSVVING-LGKFHSEPVS--DPLKQVETLLKSLNIK
tr|U2JZQ2|U2JZQ2_9FIRM              YENKHKDELSLGI-GNYIRFSFFADKIQV---VRNERMEEFIITDLNNDIFNIFKKVEMK
AAS61889.1                          YE--RQPCWYLGK-GCQARLHINADGTQATF-IDDAGEQKWAVDSIADCARRFMAHPQVK
WP_054452513.1                      YE--DNGECWFAG-GIVRSITVFATHIESNTSAGKTQRQVNS-ENLCQVLQQELNTWD-G
tr|F6CXE6|F6CXE6_MARPP              YE--KDGECWFGG-GIERSVTLYADRLESSY-KGQSLVVEATDKTLFELLNTELSSWEGA
tr|H6R5M0|H6R5M0_NOCCG              YE--QPGRWYVAG-NPVGAITVGPDRVRSTL-GGDHT-ESWS-GTPWPQIRAALARAPIP
tr|A0A426PWW0|A0A426PWW0_9CORY      ----RHGGADTGI-GRHGGADTG---------VGRHG-------------GADTGTGAAA
CCP45174.1                          YE--CDGQWVLAA-GVQAMVELDSDELRVIR-DGVTRRQQWS-GRPGAALGEAVDRLLLE
AMK48233.1                          YE--REGDYCFAG-GALGEVVVGRSGIRRRW-LSEEIVEPLG-PHPLRQVGEKLAEMGAE
WP_009076320.1                      YE--NGGTWTFAG-GALAAITLDSTHVRVRG-VVESD-TEWS-GSPGAALQQALATLPVP
BAD55464.1                          YE--RPGQWVFAA-DPIGSIELDASELRVTW-EGETTVSRWE-GSPARALDRALGMLPAG
WP_011146566.1                      YE--VKGEWSLGI-GCAATISADASGQLI---DSQGNRHPYDISTLSQKLEQALNALPIQ
AKQ52535.1                          YE--HNGEWAIGI-NKLQQLTVDTQGRITDF-TGKVD-QPNP-KDLCDAIHQATQALPWD
                                               .  .                                             

AGE11890.1                          HLP-----------------------RRPARQRPRPVVPAAPRWLGNGR--IQPGDRRPR
WP_015217392.1                      NWTAYGYIAFDIARFY------SAYSKAISQELLYFLIPETELRFTETG--VHIKT--TK
tr|U2JZQ2|U2JZQ2_9FIRM              GWKAYGIVNFSYAKNS-----FLD--EKINEKLMDLFIPNIDIRVEKNR--ILIRY--ME
AAS61889.1                          GRRVYGQVGFNFAAHA---RGIAF--NAGEWPLLTLTVPREELIFEKGN--VTVYADSAD
WP_054452513.1                      EWQACGWSSFEFAYALKSPELLTEEEKAGQEALLFICEPKITVSLGKKP--TLIKSKSSE
tr|F6CXE6|F6CXE6_MARPP              -WQANGWACFELAYAVNEPNVLNDDEQAGKVPLLFLSQPKAIVSLGQHT--PEIQTKDES
tr|H6R5M0|H6R5M0_NOCCG              GWRAYGWACFELQNPS------IA--PPGE-VLAYIMVPGVELEITGDA--VHIRS----
tr|A0A426PWW0|A0A426PWW0_9CORY      GAEGHARTDAGED-------------PAAELPLAVLRWPETVERITADPATVPVGGPAAE
CCP45174.1                          TDQAFGWVAFEFGVHR---YGLQQR-LAPHTPLARVFSPRTRIMVSEKE--IRLFDAGIR
AMK48233.1                          GWNAHGWMAFEFSHLY---TDRPD--RAGDADLLHLAVPHTEVRFRQEH--AEVRGADRE
WP_009076320.1                      EWRAYGRVHFGYSALP-PGSGLPK--PSG--ELVRLIVPRTEVRVTGNE--VEIRG---E
BAD55464.1                          SAKAYGWIGFEFCAWALAATDHVD--ERT--SLAHLMIPRIEVVVDESG--VRIGGATPS
WP_011146566.1                      DWRAYGRTLFEFSHMT---YGLPL--AQQNEALIKITIPQHELRITPGQ--VLIRTLEES
AKQ52535.1                          GWRVFGRVDFEFSHFA---HQLSH--KMTHRNLLELFIAQHDIRVTHDQ--VVIRTVAPS
                                                                          .     .               

AGE11890.1                          HRRR-------------QAGRGPAPRGDPGPGGRSAHG----QQSPCRALPGREGGLRTR
WP_015217392.1                      SLDQIEEL---------LFVETFLPDYDLTSLVIDFSDNENYKNRVDTLITAIQNGD-LQ
tr|U2JZQ2|U2JZQ2_9FIRM              EFECIVSMVEDCLSNLKELKEIITENDKSKLELIKSVDENYYKNIVSKATEEIKNNK-YE
AAS61889.1                          GCRRLCEW---------VKEAGTTTQNAPLAVDTALNG-EAYKQQVARAVAEIRRGE-YV
WP_054452513.1                      LEQQVRLI---------LENAVVRAHVPYKNVEIPDNI--NYKNAVKKSVANIQNGL-LE
tr|F6CXE6|F6CXE6_MARPP              LKQKINEL---------LNTPK-VSNASTNGVSIPDSE--EYKQWVNNSLTQIEKGT-LE
tr|H6R5M0|H6R5M0_NOCCG              -YGAPFDL---------DLPENYRPATEPTPMPVDEID-TAYLRRVRAALDRIGAGE-FD
tr|A0A426PWW0|A0A426PWW0_9CORY      GASTPGTP---------NPTPTPTPNPTPSPVDVSGGG-DAYRATVTRAVEEIRAGR-YE
CCP45174.1                          HREAIDRL----------LATGVREVPQSRSVDVSDDP-SGFRRRVAVAVDEIAAGR-YH
AMK48233.1                          TLNAVLEL---------LAEPVSRTPVAPRPIEVADVS-GRYPEIVARAIEEIRSGTDLQ
WP_009076320.1                      DEALVRGI---------IDAPSPAPHSPSRPIDVRASG-AAYRGRVARALGEIRRGR-YQ
BAD55464.1                          ETADIHDL---------IAAAQDTELPQPHPIDVRIDP-TGYRDRVAEAVAEIGAGR-YQ
WP_011146566.1                      QLTILREKISQVDQ---LGTPVFPWTKDREIISTSDAA-KRYQDNVANAVKDIASGH-YQ
AKQ52535.1                          FLPHIERVIAEVTTPLPVAEPI-APLTQADILNHEQIQ-HDYQAMVAAAVKEIVADD-YK
                                                                                           .    

AGE11890.1                          RVGTAR--GRGARTGLHPGLRQGRRLHVGEGAGKRPAPGLTAVRFARTGTHGVGGGRRAL
WP_015217392.1                      KAIISRSVKVTGNLDILGTYVVGSKANNSARSYCLNLEDIRAVGFSPEILMQVNENGFVV
tr|U2JZQ2|U2JZQ2_9FIRM              KVILSRKINLEKRISFMDSYLEGRKYNNPARSYCMKIDDLEVVGFSPETVVEVDRDKTVY
AAS61889.1                          KVIVSRAIPLPSRIDMPATLLYGRQANTSVRSFMFRQEGREALGFSPELVMSVTGNK-VV
WP_054452513.1                      KVILSRKVPLHFSPDYTATWLQGRSMNTPARSFTMNLAGWKITGFSPEIVLSVNENRKVT
tr|F6CXE6|F6CXE6_MARPP              KVILSRKLKLDFSPDFVATWLRGRKENTPARSFSLNLGDWQASGFSPELVMSIDKNRIVT
tr|H6R5M0|H6R5M0_NOCCG              KVIMSRRVDLPFAVDMPATYAAVRRANTPARSFLLDLGGWQAAGVSPETVLEADGAGLAT
tr|A0A426PWW0|A0A426PWW0_9CORY      KVIISRRVAVPGRPDIPATYRAGRAANSPARSFAFEWPELSAAGFSPEIVVSVDADGLVT
CCP45174.1                          KVILSRCVEVPFAIDFPLTYRLGRRHNTPVRSFLLQLGGIRALGYSPELVTAVRADGVVI
AMK48233.1                          KVILSRSVPVPFPVDFVATYVHGRTHNTPARSFLLRLGGRHVAGFSPETVAEVSADGEVV
WP_009076320.1                      KVILSRSVRIPFPVDLASTYEAGRRANTPARSFLLRLDGAEAAGFSPEVVLTVSADGTVV
BAD55464.1                          KVILSRKVDLPFTVDVPATYRLGRANNTPARSFLLRLGGLESAGFSPELVASVDEDRVVT
WP_011146566.1                      KVILSRRVELGSDIDMPHSYWLGRQANTPARSFFLRDEDFSVYGFSPETVVEADGSGWVS
AKQ52535.1                          KVILSRRATLPAAIDIRRSFISGRGKNTPARSFLLKLGELEAFGFSPETVLEVDNLGHLS
                                    ..  :*        .           :    :             :              

AGE11890.1                          ------PRGDGLGHPQGRGVRTHSPHRARGPSDLVXRRAVSRRSTPTARSTPRVVLRTRL
WP_015217392.1                      TNPLAATRPRGADSEEDIRLSGELFTDAKEVKEHSLSAWLAQNEITSLCLPETVRVFDFM
tr|U2JZQ2|U2JZQ2_9FIRM              TFPLAGTRALTEDKELNKKLKDELLKDPKEIAEHAVSVKLAYEELEKVCDKDSVSVIQFM
AAS61889.1                          TEPLAGTRDRMGNPEHNKAKEAELLHDSKEVLEHILSVKEAIAELEAVCQPGSVVVEDLM
WP_054452513.1                      TEPLAGTRRLEGNPDTDQKIFDELLRDPKETHEHAISVRLSVDEMTEVCEPESVHVPQFM
tr|F6CXE6|F6CXE6_MARPP              TEPLAGTRRRDGIFAEDISRFNELYRDPKETHEHAISVFLATNELKAVCHEPSIVVRRFM
tr|H6R5M0|H6R5M0_NOCCG              TQPLAGTRARTGDPGRDRALRDELLADPKEIYEHATSVRLAFAELAGVGS--ATRVSEFL
tr|A0A426PWW0|A0A426PWW0_9CORY      TEPLAGTRALTGDPEEDRRLHDDLVTDDKEIAEHCLSVRDAMEEVGSVCD--GARVDEFM
CCP45174.1                          TEPLAGTRALGRGPAIDRLARDDLESNSKEIVEHAISVRSSLEEITDIAEPGSAAVIDFM
AMK48233.1                          TQPLAGTRARGFGGAEDERLRAELLADPKEISEHVLSVKLAEEEMGTVCRPGTVSVRDLL
WP_009076320.1                      TQPLAGTRAFGRGSEQDAAARKDLESNPKEIFEHAVSVRTAQEELLRVCRPDSVRVKDFM
BAD55464.1                          TEPLAGTRAFGRGHEVDMAARADLVSDPKEIVEHAISVQTSFAEISAVADPGTPAVSDFM
WP_011146566.1                      TQPLAGTRALTHDKDQDQRLRADLLSDPKEISEHAVSAKLALEELAPICQADTLCVSEFM
AKQ52535.1                          TQPLAGTRFLPADPIEAERLKKELTTDPKEIAEHATSVKLAIEELEQVCEQETVNVAQFM
                                          .*                    .   :       :  .           :   :

AGE11890.1                          PAAXGRTVASGGRRHRGPFQPGARAGGDAGEAPQRVALPGPGHRRRGRAAVPGLRPG-RA
WP_015217392.1                      EVKKYRCVQHLSSRVGGQLLPKNTLWDALKVLFPGITVSGI-DKKQALEWINNLEDEPRG
tr|U2JZQ2|U2JZQ2_9FIRM              DVLERGTVQHLASRLRGKIKDEFNEWHAFTALFPAVTASGI-PKKECIEAIDRLEKDERG
AAS61889.1                          SVRQRGSVQHLGSGVSGQLAENKDAWDAFTVLFPSITASGI-PKNAALNAIMQIEKTPRE
WP_054452513.1                      VQKKRGSVQHLASRVCGTLKTEYNAWHAFESLFPAVTASGI-QKLAAFSEIRRHEGSSRG
tr|F6CXE6|F6CXE6_MARPP              ERKERGSVQHLASTVCGELKDGLNPWDAFASLFPSVTASGI-PKKPAFKEIRRNEVESRG
tr|H6R5M0|H6R5M0_NOCCG              TVKERGSVQHLASRVETLLPADRDGWDALAAVFPAITASGI-PKAPACAAIDELEPGARG
tr|A0A426PWW0|A0A426PWW0_9CORY      AVRRRGSVQHLASTVRGRLAGGRDRFDALGVLFPAVTASGI-PKREALDAVHRLEPVARG
CCP45174.1                          TVRERGSVQHLGSTIRARLDPSSDRMAALEALFPAVTASGI-PKAAGVEAIFRLDECPRG
AMK48233.1                          SVRRRGSVQHLGSSVHGLLADGATAWDVLRAVFPAVTASGI-PKLPAYERITRLEGGHRG
WP_009076320.1                      GIKERGSVQHLASSVSGELAEGRTPWDALEAVFPSVTASGI-PKREAIDAITRLDEV-RG
BAD55464.1                          AVRERGSVQHLASTVRGRLAADRSSWDALEVLFPSVTASGI-PKREGVDSVFRLDGAPRG
WP_011146566.1                      AIRERGSVQHLASRVKGLLQTDKNRWDAFIALFPAVTASGI-PKKTSLQAISRYEGEPRR
AKQ52535.1                          EVSERGSVQHLASRVTGQLAQDKSAWNAFKVLFPAITASGI-PKREAIEAITRYEPTSRG
                                           *   .      :                :: .*   .      :       * 

AGE11890.1                          VRSVGPLSSA-RDGRRRAGRACVRDRPVPRRTAARIGR-WSRAASG-----SPTRLIRRP
WP_015217392.1                      IYAGGIGWVD-SNGAADIA-------IAIRSVYQYGNKIHLNAGAGIVAESIPEKEYIES
tr|U2JZQ2|U2JZQ2_9FIRM              LYSGGVLTYD-KDGTLDVA-------LVLRTAFQNEKETWVRVGAGIVKLSNPERELEET
AAS61889.1                          LYSGAILLLD--DTRFDAA-------LVLRSVFQDSQRCWIQAGAGIIAQSTPERELTET
WP_054452513.1                      LYAGAILKLD-HTGVIDAA-------LVLRSVMSKGDQHWLQAGAGIVLDSTPERELTET
tr|F6CXE6|F6CXE6_MARPP              LYAGAVLRLS-HDGTFDAA-------LVLRSLLGHKGKSWLQAGAGIVSNSTPERELTET
tr|H6R5M0|H6R5M0_NOCCG              LYSGAVLRAD-STGNLDAA-------LVLRAVYQRDGRSWLRAGAGVVTGSTPEREHEET
tr|A0A426PWW0|A0A426PWW0_9CORY      MYAGAFVVLG-ADGSLETA-------LSLRTVYATDRAAWVQAGAGIVRSSRPEREFTET
CCP45174.1                          LYSGAVVMLS-ADGGLDAA-------LTLRAAYQVGGRTWLRAGAGIIEESEPEREFEET
AMK48233.1                          IYSGAVLQAS-SDGSLDAA-------LVLRSVFEEDGRTWLRAGAGILAGSTPARELEET
WP_009076320.1                      LYSGAVVTAA-HDGSFDAA-------LVLRAVYQENGQAWLRAGAGIVTESTPERELEET
BAD55464.1                          LYSGAVVTVSPTTGALEAT-------LVLRAVYQTAEGAWLRAGAGVVGQSRPEREFEET
WP_011146566.1                      LYSGCVMLLD-SSGKLDAA-------LVLRSLYQHQGRCWLQAGAGLVRDSKPEREWQET
AKQ52535.1                          LYSGSVLIAD-QDGFFDAA-------LVLRAAYKRHSLSMLQAGAGIISLSTPDREWQET
                                    : :                          *           ...:*      * .    .

AGE11890.1                          NAAPACSTSRFRPP--------
WP_015217392.1                      VNKMNTMLNNLVLEA-------
tr|U2JZQ2|U2JZQ2_9FIRM              KEKVGSIINRLVYIED------
AAS61889.1                          REKLASIAPYLMV---------
WP_054452513.1                      SEKLASISPWVVEKTS------
tr|F6CXE6|F6CXE6_MARPP              TEKLSSVAPWVMKQMA------
tr|H6R5M0|H6R5M0_NOCCG              REKLSCVAPYLIADHSGPATGR
tr|A0A426PWW0|A0A426PWW0_9CORY      CEKLGSVAPYVVVRG-------
CCP45174.1                          CEKLSTLTPYLVARQ-------
AMK48233.1                          CEKLRSVAPYVVPAQPAARG--
WP_009076320.1                      CEKLGSVAPYVVPA--------
BAD55464.1                          CEKLGSIAPYVVKA--------
WP_011146566.1                      CEKLDCIMKYVRPCSGKKE---
AKQ52535.1                          CEKMACVLDHLIFETAIKD---
                                              .           
