CLUSTAL multiple sequence alignment by MUSCLE (3.8)


NupP_Nunamycin_KPN90375.1_Asp_CA      IEPVTPGLDFAAWASARREAVEALLCRHGAVLFRGFGLDTVASFEAFAEALSPGLHGSYG
SyrP_Syringomycin_AKF46133.1_Asp      ----ADGLDPVQWASARREAIETLLCRHGAVLFRGFDLPSVAAFEGFAEALSPGLHGTYG
ThaF_Thanamycin_ALG65284.1_Asp_C      ------GLDPAQWAGQHRGAIEALLCRHGAVLFRGFDLGSVPAFEAFAEALSPGLHGSYG
                                            *** . **. .* *:*:*************.* :*.:**.***********:**

NupP_Nunamycin_KPN90375.1_Asp_CA      DLPKKEGGRNVYRSTPYPEREMILYHNESSHLESWPRKQWFFCEKPSRVGGATPLVDIRQ
SyrP_Syringomycin_AKF46133.1_Asp      DLPKKEGGRNVYRSTPYPEREMILYHNESSHLESWPRKQWFFCEQPSRVGGATPLADIRQ
ThaF_Thanamycin_ALG65284.1_Asp_C      DLPKKEGGRNVYRSTPYPEREMILYHNESSHLESWPRKQWFYCEQPSRVGGATPLADIRQ
                                      *****************************************:**:**********.****

NupP_Nunamycin_KPN90375.1_Asp_CA      MIRLLPAEIVETFERKALSYSRTFTKGVEPSWQNFFGVDDPAVVEARCCEQGTDCAWLDA
SyrP_Syringomycin_AKF46133.1_Asp      VLAYLPKEVVERFESKGLLYSRTFTAGVEPSWESFFGTSERSVIEQRCREQGTDFEWLDG
ThaF_Thanamycin_ALG65284.1_Asp_C      VLQRLPEQVVARFEQKGLMYSRTFTAGVEPSWESFFGTTDRAAVEQRCREQGTDFEWLDA
                                      ::  ** ::*  ** *.* ****** ******:.***. : :.:* ** *****  ***.

NupP_Nunamycin_KPN90375.1_Asp_CA      DTLQIRTRCPAVIKHPVTGESAFFNQVQLHHPFCLGEEMREDLLDMFGEDRLPRMVSYGD
SyrP_Syringomycin_AKF46133.1_Asp      DTLQLRTQCPAVITHPFTGERCFFNQVQLHHPYCMGEELREDLLDMFGPDRLPRLVSYGD
ThaF_Thanamycin_ALG65284.1_Asp_C      DTLQVRTLCPAVIRHPLTGEPGFFNQVQLHHPFCLGEEMREDLLDMFGADRLPRMVSYGD
                                      ****:** ***** **.***  **********:*:***:********* *****:*****

NupP_Nunamycin_KPN90375.1_Asp_CA      GTPIEDEVMALLGEAYESCAVRFDWQKGDVVMLDNMLTAHARDPYEEPRLIVVA
SyrP_Syringomycin_AKF46133.1_Asp      GSAIEDPVMALIGEAYEACAVRFEWRKGDVVMLDNMLAAHARDPYEEPRLIVVA
ThaF_Thanamycin_ALG65284.1_Asp_C      GTPIEDDVMALVGEAYEACAVRFAWRKGDVVMLDNMLAAHARDPYEEPRLIVVA
                                      *:.*** ****:*****:***** *.***********:****************