CLUSTAL multiple sequence alignment by MUSCLE (3.8)


tr|K9XE27|K9XE27_9CHRO           MEFSILYFSGDGSTIESDKYQLLLETAKLADKHGFSAVWTPERHFHPFGGLYPNPSVISA
tr|K9PK50|K9PK50_9CYAN           MEFSLFYFSGDGSTTRNDKYRLLIEGAKFADQHGFSGIWIPERHFDAFGGLYPNPSVLGA
tr|K9UHI7|K9UHI7_CHAP6           MEFSLFYFSGDGSTTSRDKYRLLIEGAKFADRHGFAAVWIPERHFDAFGGLYPNPAVAGA
WP_104904842.1                   MEFSLFYFSGDGSKIESNKYNLLIESAKFADKNNFSAVWTPERHFHAFGGLYPSPSLTCT
KPQ36572.1                       MKFSLFYFDGDGLNTQANPYKLLIESAKFADENGFSAVWTPERHFHAFGGLYPNPAMTSA
QCO55750.1                       MQFSLFYFDGDGATRNPDAYRLLMDSAAFADTNGLSALWVPERHFHAFGGLYPNPAVIHA
FbnE_tr|A9CFI5|A9CFI5_AGRFC      MKFSLFYFDGDGSRPGQENYRLLMDSAQFADKNDLEALWVPERHFHAFGGLYPNPSIVSA
ACM39985.1                       MKFSLFYFDGDGSATNGDSYRLLMDSARFADDNGLSALWVPERHFHAFGGLYPNPSMIHA
                                 *:**::**.***     : *.**:: * :** :.: .:* ***** .******.*::  :

tr|K9XE27|K9XE27_9CHRO           ALAMVTEKIQLRSGSIVMPLQHPVRVAEEWAVVDNLSGGRVGLSFAPGWHADDFLLRPEN
tr|K9PK50|K9PK50_9CYAN           AIAMITQRIQIRSGSVVLPLQHPLRVAEEWSVVDNLSNGRVSLSFAPGWHPNDFVLYPEN
tr|K9UHI7|K9UHI7_CHAP6           AIAALTDNIQIRSGSVVMPLQDPLRVAEEWAMVDNFSQGRVGLSFAPGWHPNDFVLAPEK
WP_104904842.1                   ALAMVTKQIQLRAGSVVMPLHNPARVAEEWSVVDNLSNGRVAIGFASGWTIDDFVLSTES
KPQ36572.1                       ALAMVTHNVQLRAGSVVLPLHHPVRIAEDWAMVDNLSNGRAAIAFASGWTMDEFILSREP
QCO55750.1                       ALAVATKNVKLRSGSVVMPLHHPVRVAEDWAVVDNLSGGRAGIAMASGWTMEEFVLSREP
FbnE_tr|A9CFI5|A9CFI5_AGRFC      ALAMVTRKVQLRAGSVVAALHHPARVAEEWAVVDNLSGGRAGIAIAAGWTKDEFVFSKEP
ACM39985.1                       ALAMVTKRVQLRSGSIVLPLHHPVRVAEEIAVVDNLSQGRVGVAIASGWTRNEFVLSREP
                                 *:*  * .:::*:**:* .*: * *:**: ::***:* **..:.:*.**  ::*::  * 

tr|K9XE27|K9XE27_9CHRO           YAERKEVMWRDIKIMQKLWQGEEIEFINGSGNKVQIQTFPRPIQSQLPIWITCQADATFI
tr|K9PK50|K9PK50_9CYAN           YANNKEIMWRDIQTIQQLWQGKSITLKGGKGDSVEIKTFPRALQPQLPIWITSLADETFI
tr|K9UHI7|K9UHI7_CHAP6           YADKKAIMWRDIQVVQQLWQGESIELIGGHGKPVSINTFPKPLQPQVPIWITSLSDESFI
WP_104904842.1                   HANRKETMWRGIQTVQKLWEGEQVELKDATGKSFNVKTFPRPIQPKLPTWIVCQSSATFI
KPQ36572.1                       HGSRKSVMWRGIETVQKLWQQEAVDFEDATGRTVSTQTLPKPVQPKLPIWVTCQSMETFI
QCO55750.1                       HGFRRTQMWQGYEQVTRLLAGDSVEFEDADGNLVAAKTLPRPLQPRIPFWVACQSTETFI
FbnE_tr|A9CFI5|A9CFI5_AGRFC      HGNRRSTMWRSYEQITRLLAGEAVSFEDADGNIVEAKTLPRPVQSRIPFWVACQSTETFI
ACM39985.1                       HGSRRSLMWRSFDQVTKLLAGETLTFEDAEGNTVEAKTLPRPVQPRVPFWVACQSMETFV
                                 :. ..  **.. . : .*   . : : .. *  .  :*:*..:*..:* *:.. :  :*:

tr|K9XE27|K9XE27_9CHRO           GAAKIGANVLTSLLYATIDDLAQQISLYRLTLAQSGHDPKSCKVSLMMHTYIGDNEQLVK
tr|K9PK50|K9PK50_9CYAN           EAGKIGANILTSPLYQSLEDIFRKISLYRQSLAQHGHNPQQHKVAVMIHTFVGKDIKLVK
tr|K9UHI7|K9UHI7_CHAP6           EAGKIGANILTSPLYQSLDEILCKITLYRQALAQSGRDPQSGKVSMMIHTFIGDDLESVK
WP_104904842.1                   EAGKIGANILTSLLGATLEEVAPQISLYRQSLEQHGYDPNAGKVAMMIHTFLGEDFDTIK
KPQ36572.1                       EAGRLGLNVLTSLLGETLSQVEPKIARYRETLSKHGYDPHSRTVSMMMHTFLGADVDQVK
QCO55750.1                       EAGRRGINVLCSLLGETLDDVAVKIRAYREALDQNGHDPDAGKVTMMVHTFLADDVETAK
FbnE_tr|A9CFI5|A9CFI5_AGRFC      EAGRRGLNVLTALLGETTESLAPKIAAYRKSREKHGHDPAAGTVSMMVHTFLGDDTGKVK
ACM39985.1                       EAGRRGINVLTALLGETLESLTPKIAAYRRSLEKNGFDPAAGTVSIMVHTYLGGDVETVK
                                  *.. * *:* : *  : ..:  :*  ** :  : * :*   .*::*:**::. :    *

tr|K9XE27|K9XE27_9CHRO           QQVKQPFCDYLRTHFGLVENLAKRINFQFNPENFTEEDRQQLLEFAFERYFQQGRVLIGT
tr|K9PK50|K9PK50_9CYAN           QRVEKPFKNYLKTHFDLMVKTAGNLRFSVDPQKMTAQDLEDLLEFSFESYF-NNKVLMGT
tr|K9UHI7|K9UHI7_CHAP6           IKVKQPFKNYLKTHFDLVVKSAGDLRFSIDPKTMTARDLDDLLEFSFETYF-NGKVLMGT
WP_104904842.1                   EAAREPFYNYLKTHIELLENLAKNAGINVDLKKFTEADMNSLLRFAYEGWL-KGRTLIGS
KPQ36572.1                       EDIRQPFCEYLKTHYGLLENLAKGMGLNVSLSDFSDDDLDSLLLFGVEGFI-KGRSLIGT
QCO55750.1                       ANVIEPFTEYLRTHYHLLESLAKSMNLNVKLSDFSEDDLETLLKFGVEGFM-NGRSLIGS
FbnE_tr|A9CFI5|A9CFI5_AGRFC      SNVSKPFGDYLRTHYHLLEGLGRSMGVDITLDNFSDDDLDSLIEFGIEGFM-KGRSLIGT
ACM39985.1                       ANVKGPFSDYLRTHYHLLEGLARSMGLDIALENFSRDDLDSLIEFGVEGFI-KGRSLIGT
                                      ** :**.**  *:   .    ...  . ::  * : *: *. * :: :.. *:*:

tr|K9XE27|K9XE27_9CHRO           LESCRQTITRLKEIGVDEIACLVDFGLDFKTVLTSLNKLIDFKQNYQLRRDTRKYSNLSL
tr|K9PK50|K9PK50_9CYAN           PEICQKMIDSFQAAGVDEIASLIDFGVDFDWVMESLDYLKEIKNSYQKKAGSRSKEVLIK
tr|K9UHI7|K9UHI7_CHAP6           PTQCRTIIDSLQQAGVDEVAALIDFGVEFEWVMESLDFLKDIKHSYTSIDRVKTLVS---
WP_104904842.1                   KTTCMEMIERLKNAGVDEVACLIDFNDNFDDVMTSLPYLKDLKNMCNLEKEKMMSLS---
KPQ36572.1                       PESCRTFVQQLSDAGVNEVACLIDFVQDFDAVMGSLPYLAQLKQHCDQDNDRAMHIEIHP
QCO55750.1                       PESVQPFVQALADAGVDETACLIDFVQDYDLVMGGLPKIARLASANAASRPPKTA-----
FbnE_tr|A9CFI5|A9CFI5_AGRFC      PESCQSTVDTLAEMGVDEIACLIDFVQDYDLVMGSLPFLLKLVEANRPPMRVARAV----
ACM39985.1                       PESTAETVEALGAAGIDEIACLIDFVQDYDLVMGGLPHLARLARQHAPQPTIAQVV----
                                        :  :   *::* *.*:**  ::. *: .*  :  :                  

tr|K9XE27|K9XE27_9CHRO           FG----
tr|K9PK50|K9PK50_9CYAN           NLVINL
tr|K9UHI7|K9UHI7_CHAP6           ------
WP_104904842.1                   ------
KPQ36572.1                       APIGTG
QCO55750.1                       ------
FbnE_tr|A9CFI5|A9CFI5_AGRFC      ------
ACM39985.1                       ------
                                       
