CLUSTAL multiple sequence alignment by MUSCLE (3.8)


tr|Q0S7I4|Q0S7I4_RHOJR              ----------------------MSESPETVGTDLPVRDVVGVGFGPANLALAIAIEEHNA
fuscachelin                         -------------------MTPSLDHEVSDTSERPVHDLVGVGFGPSNLGLAIALRERRA
scabichelin                         -MLGEAVFLPGRLCGPLFSMKGDDAVTMLHTGPDSIYDVLGIGFGPSNLALAIALHEHSA
gobichelin                          MDEWSCSPRPPSLGSNGRTSMSGRREDSGQAEGGAAQDLVGIGFGPSNLALAIAVADHNR
qinichelin                          --------------------MSVRRGDTAHTGCGPIEDLVGIGFGPANLALAIAIDEHNR
amychelin                           ------------------------------MATPPEFDLVGVGFGPSNLALAIAVAEHNG
albachelin                          ------------------------MARAVFGERVPVYDVVGVGFGPSNLALAIAVTEHNA
erythrochelin                       --------------------------MTRYDDSNPVRDLVGVGFGPSNLALAIAVREHNA
coelichelin                         ------------------------MSQVLPADSTLVHDLIGIGFGPSNVAMAIAIREHNA
salinichelin                        ------------------------MSQTLPGDAPLIHDLIGIGFGPSNLAMAIALNEHNA
tr|A0A0F4QHH1|A0A0F4QHH1_9GAMM      ---------------------------------MKLYDVIGIGFGPANLALAIALQEQNK
tr|C1DIQ9|C1DIQ9_AZOVD              --------------------------MTPGLSSTEIYDMIGVGFGPSNIALAIALEEMAS
tr|A0A375CHW0|A0A375CHW0_9BURK      --------------------------MTLREIPPAAHDLVGIGFGPSNLALAIALQEQAA
tr|Q0K0K9|Q0K0K9_CUPNH              ----------------MLYSASTFAAHGTDAGAGPVLDLLGIGFGPSNLALAVALREMLP
tr|Q0VMR1|Q0VMR1_ALCBS              -----------------------------MSVHSQEYDVVGIGFGPANLAIAIALDEHKD
tr|A0A0C4WTD7|A0A0C4WTD7_9GAMM      -----------------------------MSIETLEYDVIGVGFGPANLAIAIALEEDSR
tr|B2JPG8|B2JPG8_PARP8              -------------------------MTHLTTQREHIHDLIGVGFGPSNLALAVRLAESGS
tr|N6W943|N6W943_9ALTE              --------------------------------MSHIHDYVGVGFGPSNLALAIATQEFAQ
                                                                         * :*:****:*:.:*:   :   

tr|Q0S7I4|Q0S7I4_RHOJR              ECPPRERISAQFFEKQDRFGWHPGMLLDGATMQIAFPKDLVTFRNPRSAFTFFNYLFDQG
fuscachelin                         AGGK--APTGLFLERQERFSWHQGMLLDDATMQISFLKDLVTPRNPASDFSFLSFLHRMG
scabichelin                         RAGAENGPRVGFLERQPRFGWHRGMLIDDATMQVSFLKDLVTMRDPTSDFSFLCYLRDQG
gobichelin                          RDPER-VLRARFVEQQERFGWHRGMLLEGATMQVSFLKDLVSMRDPSSRFSFLMYLQERG
qinichelin                          RNPGS-AIRAGFLERQQRFGWHQGMLIEGATMQVSFLKDLVTMRDPGSRFSFLHYLQERG
amychelin                           TSAA--PVTAQFLERQPAFGWHRGMLLDDATMQVSFLKDLVTMRNPASRFSFLSYLHEHG
albachelin                          APGAE-TVTAHFLERQACFGWHRGMLIDNATMQVSFLKDLATMRNPTSSFSFLSYLHSKD
erythrochelin                       QVGAGDQVDARFLESKPAFGWHRGMLIDDATMQVSFLKDLVTQRNPASEFSFLSYLHSKG
coelichelin                         QAGGQEELDARFFEQQPRFGWHRGMLIDDATMQVSFLKDLVTLRNPASRYSFLCYLQSRG
salinichelin                        RVGRQEAVTAHFFEQQPRFGWHRGMLIDDATMQVSFLKDLVTLRNPPSEYSFLCYLRDKG
tr|A0A0F4QHH1|A0A0F4QHH1_9GAMM      L-----SDRVCFIEKQQDFLWHGGMLLDNTTMQISFLKDLVSLRNPTSHFSFINYLHHNK
tr|C1DIQ9|C1DIQ9_AZOVD              QHG---PLKSLYLDKQEDYRWHGNTLVTQSELQISFLKDLVSLRNPTSRYSFVNYLHHHG
tr|A0A375CHW0|A0A375CHW0_9BURK      AGR---PLDAHFIEKQQDYQWHGNTLVAQSEMQISFLKDLVSMRNPTSPYSFINYLHRHG
tr|Q0K0K9|Q0K0K9_CUPNH              QQA---PFRFGFVEKKPGFVWHGNMLLDNSRMQISFLKDLVTMRNPASRYTFINYLHERE
tr|Q0VMR1|Q0VMR1_ALCBS              LD----GLRYCFLEKQPRFEWHGGMLLEGTRMQVSFLKDLATLRNPASRFTFVNYLHDNN
tr|A0A0C4WTD7|A0A0C4WTD7_9GAMM      TRES--GLRYCFLDSKPAFEWHGGMLLENSRMQISYLKDLATLRNPASRFTFVNYLHEKQ
tr|B2JPG8|B2JPG8_PARP8              A-----PAAHCFIERQPEFGWHRGMLLDDSRMQISFLKDLVTQRDPTSRFTFINYLFERG
tr|N6W943|N6W943_9ALTE              GVR---SPDVCFLERKPAFAWHEGMLIDGSTMQISFLKDLATLRNPQSRFTFINYLMEQG
                                               :.: :  : ** . *:  : :*::: ***.: *:* * ::*. :*    

tr|Q0S7I4|Q0S7I4_RHOJR              RLVDFVNHQTFFPTRHEFHDYLQWAARRVDADVRYGTAVETV--RGIRGDDGV---IDRF
fuscachelin                         RLHDFINHKTLFPLRAEFHDYLVWCAQRVSDQVRYGQHVVAL--RPVT-RHGK---VVYL
scabichelin                         RLVDFLNLKTLFPLRIEFHDYFAWAAARVSHLVEYSAEVVSV--RPVS-RDGE---VRYF
gobichelin                          RLADFINQKTFFPTRIEFHDYFEWCAAEFSGDVDYGRRVVEV--RPVR-NADR---VETV
qinichelin                          RLADFINQKTFFPTRVEFHDYFEWCAGEFASAVDYGRTAVAL--QPVR-NDGV---TESV
amychelin                           RLVDFINHKTFFPLRVEFHDYLEWAAAKVSGQVAYGSEAVSV--RSTG---------DCF
albachelin                          RLVDFINHKNLFPLRIEFHDYFEWAAEKVDDLVSYGTEVLSV--TPVF-DGDE---IEFF
erythrochelin                       RLVDFINHKSLFPLRVEFHDYFEWAASHLDDSVDYGVEVVGV--EPVV-RDGV---VEHF
coelichelin                         RLIDFINHKNLFPLRVEFHDYFEWAAAKVDDMVSYGHEVVGV--APVV-RDGV---VDHL
salinichelin                        RLIDFVNHKTLFPLRVEFHDYFEWAAAKVDDMVSYGHEVLTV--EPVV-RDGV---VEYL
tr|A0A0F4QHH1|A0A0F4QHH1_9GAMM      RLDNFINLKTFYPSRHEFNDYLGWAASHFRDYCHFGEQVCAV--EPVL-LDGQ---VDHL
tr|C1DIQ9|C1DIQ9_AZOVD              RLVDFINLGTFYPCRMEFDDYLRWVAGHFASQCRYGEQVIGI--EPQR-NSQR--LVESL
tr|A0A375CHW0|A0A375CHW0_9BURK      RLVDFINLRTFYPSRMEYNDYLRWAASHFAGQCSHGEEVARI--EPEA-QGGR---IGRV
tr|Q0K0K9|Q0K0K9_CUPNH              RLLDFINTRTFYPSRYEFNDYLSWVAGDFADACHYGEEVVSVAPEPAG-GNGD---LACL
tr|Q0VMR1|Q0VMR1_ALCBS              RLDSFINMGTFFPTRVEYNDYMRWSADQFKEHVHYGQEVIAI--EPVE-QGGE---VEWV
tr|A0A0C4WTD7|A0A0C4WTD7_9GAMM      RLLPFINLGTCNPSRIEYNDYLRWAAGHFAERVHYGEQVVAV--EGVE-ERGE---VQRL
tr|B2JPG8|B2JPG8_PARP8              RLQHFVNLKNFYPTRIEFHDYLRWVASAFDDQVHYGESATRI--EPVV-DANEPRTVTHL
tr|N6W943|N6W943_9ALTE              RLEDFINIQTFFPTREEYNDYLSWAASKFEDQVHYGQSVQSV--EPLI-EGGK---LTGM
                                    **  *:*  .  * * *: **: * *  .     ..  .  :                 .

tr|Q0S7I4|Q0S7I4_RHOJR              EV--RTADG----STVIARNVVMGAGLRERIPE---WANPSARCFHNHQFLFRLGEM--P
fuscachelin                         DVVARDTAG--RETVERARNVVLAPGLRPSMPE---GVHPSDRVWHSEHLLHRLADL--P
scabichelin                         DVTSRTPGDPDRFTVRRTRSICVAAGLEPHLPP---DAVLSDRVWHTSELLPRVEEARRT
gobichelin                          EVVSESVSDPADRQVLRALNVSVGTGLTPRLPD---GVTQGEHVWHTRDLLFRAPEV--T
qinichelin                          DVVSRSVQDPADESVRRTRNIVLGTGLTPRLPE---GVSLGPHVWHNRDLLFRAAEL--T
amychelin                           EV--RTGHG----EVRRARNLVFGTGLRPNVPA---GIEPSDRVWHNADLLRRIGSV---
albachelin                          DVHART-DG--ELVNLRARNLVMGTGLRPNLPE---GVTPGTRVWHNSELLHRVEGM--A
erythrochelin                       DVVGRTASG--QEMTYPARNVVLATGLEPNLPE---GITSGDRVWHNSELLHRIESL--P
coelichelin                         EVTVRSGEG---LEVHRARNLVVGTGLRPLVPE---GVERGDRVWHNSELLSRVDTL--E
salinichelin                        DVTARSGDE---VVVHRARNLVVSTGLRPVMPE---GVERTERIWHSSELLAKVDGL--E
tr|A0A0F4QHH1|A0A0F4QHH1_9GAMM      KVISRDSEG--QQSVRLTKHLVVSVGGSAKVPAPFNALQDAENVWHSSQYLHNKDKV--Q
tr|C1DIQ9|C1DIQ9_AZOVD              KVISRTVDG--RETTRHTRSLVVSVGGTPKVPEVFDSLKNDARVCHHAQYLEWISKQPCV
tr|A0A375CHW0|A0A375CHW0_9BURK      RVVSVDAQG--REHTRLARAIVLSTGGTPRIPEAFAGLSGDPRLTHHSGYLSWIGTQPCA
tr|Q0K0K9|Q0K0K9_CUPNH              RVTSRTAEG--ALTERRARNVVVSVGGAPSIPDAFVPLRGHPRVFHSSSYLESLERL-ER
tr|Q0VMR1|Q0VMR1_ALCBS              RVRSRNPDG--SENEIFTRNLVIGIGGYPKIPAVFAG-KMGNNMVHSSRYKHEYERFGRH
tr|A0A0C4WTD7|A0A0C4WTD7_9GAMM      RVVSRLADG--RTHTRLTRNLVVGIGAQAAIPELFAGLKGEPRLIHSSQYLERIGQCCPE
tr|B2JPG8|B2JPG8_PARP8              RVHSRDAQG--KERHRLTRALSVGMGGVPQIPAAFNALR-DSVVIHSSSYLTSIGDLVGD
tr|N6W943|N6W943_9ALTE              EVLSRDKNG--EIQRRRARNLVLGMGGEPQVPQAFEGIN-DPRILHSSQYRGRIETLLAD
                                     *               :  : .. *    :*             *              

tr|Q0S7I4|Q0S7I4_RHOJR              APV----HHRFVVLGAGQSAAEIVQYLHGNYPEAEVHSVFSRYGYSPADDSPYANRIFDP
fuscachelin                         AAP----VHGFAVVGAGQSAAEVVGHLHQRFADLPVHAVFSRYGYSPSDDTPFANRIFDP
scabichelin                         GRP----IRRAVVLGAGQSAAEAVDYLHRSFPEAEICSVFAKYGYTPADDSPFANKIFDP
gobichelin                          NRR----YRRFVVVGAGQSAAEAVDYLHRTFPDAEVNAVFTRYGYSPADDSPFANRIFDP
qinichelin                          GRP----HRRFVVVGAGQSAAESAEYLHRTFPDAEVCAVFSRYGYSPADDSPFANRIFDP
amychelin                           -RA----PGRCVVIGAGQSAAETTAFLHERFPDAEICSVFARYGYSPSDDSSFANRIFDP
albachelin                          AEE----PRRFVVVGAGQSAAEVSALLHDRFPQAEVCAVFARYGYSPADDSAFANRIFDP
erythrochelin                       QRG----DERFVVVGAGQSAAEVVAHLHGRFQDAQVSAVFSRYGYSPSDDSPFANRIFDP
coelichelin                         GTS----PSRFVVVGAGQSAAENVAYLHRRFPSAEICAVFARYGYSPADDSAFANRIFDP
salinichelin                        GTN----PSRFVVVGAGQSAAENVAYLHRRFPEAEICAVFSRYGYSPADDSSFANRIFDP
tr|A0A0F4QHH1|A0A0F4QHH1_9GAMM      DGD------RVAVIGAGQSGAEIFADLAAMTEQPEVDMIMRAGAMKPADSSPFVNEIFDP
tr|C1DIQ9|C1DIQ9_AZOVD              SGK----PMRIAIVGGGQSAAEAFIDLNDSFPSVQVDMILRGSALKPADDSPFVNEIFSP
tr|A0A375CHW0|A0A375CHW0_9BURK      SGK----PMRIAVIGAGQSAAEAFIDLHDNYPSVKVDWIIRGAALKPADDSPFVNEIFAP
tr|Q0K0K9|Q0K0K9_CUPNH              TAP----VRRVAVIGSGQSAAEIFLDLHGREGGIAVDLVSRVPALKPADDSPFVNEIFNP
tr|Q0VMR1|Q0VMR1_ALCBS              ETP------RIAVIGAGQSAAEIYLDLMDQYPDGKMDLISRSRALHPADDSAFVNEIFDP
tr|A0A0C4WTD7|A0A0C4WTD7_9GAMM      REG----RYRVAVIGSGQSAAEIYTDLAGRYPQAEISLVMRAQAMRPADDSPFVNEIFDP
tr|B2JPG8|B2JPG8_PARP8              GKRGTAQRRRVAVVGSGQSAAEVFIDLARRFPHVDATLMMRAPALKPADDSPFVNEIFNP
tr|N6W943|N6W943_9ALTE              SGR----RARVAVVGGGQSAAEIFEDITNRFPHVDASMILRGTALKPSDDSPFVNEIFNP
                                               .::*.***.**    :           :    .  *:*.:.:.* ** *

tr|Q0S7I4|Q0S7I4_RHOJR              EAVDDLHGAPEAERLRLLDVHRSTNYSVVDIELINELYATEYQERVRGRRRLFMRR---A
fuscachelin                         EAVDAYYDAPQEFKDELMHYHRNTNYSAVDPDLIAELYRRFYAERVRGKPRLQIHN---M
scabichelin                         EAVDLYYGSPREVKQSLFDYHRSTNYSVVDMDLIESLSRTMYQEKVQGRERLRMMN---V
gobichelin                          SAVDDFFTAPENVKQDLYGYHRNTNYSVVDGELIEQLYRTHYQEKVSGRERLKILN---T
qinichelin                          AAVDHFYDAPEDVKQALLDYHGNTNYSVVDGELIEQLYRTAYQEKVQGRERLRILN---T
amychelin                           EGVDAYYSAPEDVKQRLMDYHGNTNYSAVDVELIDDLYRRVYRETVKGRQRLRIFN---M
albachelin                          EAVGRFYEAPEAVKDRLMRYHGATNYSAVDIDLIDELYRRVYREKVQGVERLRLIN---V
erythrochelin                       SAVDDFYTAPEQVKQKLLGYHANTNYSVVDLDLINDLYRRVYQEKVLGRERLRVLN---T
coelichelin                         AAVDDYFTAPDGVKQRLMDYHGNTNYSVVDIDLIDDLYRQMYREKVLGTERLRFLN---V
salinichelin                        QAVDEYFTAPDEVKHRLMDYHGNTNYSVVDIDLIEDLYRQSYQEKVLGTERLRFLN---V
tr|A0A0F4QHH1|A0A0F4QHH1_9GAMM      GFTDVVFSKSPEQRDRYFNEFRSTNYSVVDEPLIDHIYASLYQQKLNGTERLAIRN---R
tr|C1DIQ9|C1DIQ9_AZOVD              AFTELMFNQPEGDRQRLIDEYHNTNYSVVDLDLIERIYGIFYRQKVSGQQRHAFRC---L
tr|A0A375CHW0|A0A375CHW0_9BURK      AYTDVVFEQAQAGRDRLIDEYLNTNYSVIDANLIDQIYAMLYRQKVSGQFRVNLVT---C
tr|Q0K0K9|Q0K0K9_CUPNH              RYIDYLFSREATEREQLLREFGNTNYAVVDTDLIEAIYEVLYQQKVTGKVRHRLLA---G
tr|Q0VMR1|Q0VMR1_ALCBS              GFTDTIYARPETERQDFLKRFSQTNYAVVDLAEIEQIYERLYLQKVTGKVQHRFLS---N
tr|A0A0C4WTD7|A0A0C4WTD7_9GAMM      AFTDVVYRQPRAARQQLIRSLSHTNYSVVNLDLIESIYQDLYQQQVIGAEQHRLLA---N
tr|B2JPG8|B2JPG8_PARP8              SFTDLIYSQPKDARRSLLDTFRDTNYSVVDRPLIEQIYELLYVQNVSGASRHRLLNNCAI
tr|N6W943|N6W943_9ALTE              SFIDQIFQQPEARRHELLTEFRNTNYAVVDLELIERIYQMFYLQKLRREERHQMLP---R
                                          .      .         ***:.::   *  :    * : :    .  .      

tr|Q0S7I4|Q0S7I4_RHOJR              SEIIAVD-ETSDGIEVAVRSGVDG---LTDTLACDALILATGFTPAPLEPLLGDLAPKIH
fuscachelin                         TRVVALT-ETDDRVDLTLEDQVSG---KQTVLTVDHVVYATGYQPVDIRPLLGDLGHHCV
scabichelin                         SRLREVE-EGTDGVRVTVEFLPTG---ERETLGADLLVHATGYRPRGIGDNLGEIGKLCL
gobichelin                          TDLQGVE-PIPDGARVVLRSLTTG---QEKSLDCDAVVMATGYRPVDPRGLLGELAADCL
qinichelin                          SRLTAVEDVRGGGARAVIRSLASG---EDFTLDCDAVVLATGYRPADPRELLGELAEECL
amychelin                           SRPVEI--VEDERVRVTVESLATG---EKTVLDADLLVCATGYRPADPSDLLGELGAQCR
albachelin                          SRPTEVV-DTGSEVRVTVEALESG---ERTRIDADFVVYATGYSPADPTSLLGELASACA
erythrochelin                       SRVLEVV-ETDTGVRVAVESLTTG---EKALLESDVVVYATGYRPSDPTALLGELAEHCE
coelichelin                         SRLSDVK-ETPDRVRATVTSLVTG---EESHLDADVVVLATGYGPADPLGLLGEVADRCL
salinichelin                        SRLTHVE-ETPDGVHVTVRSLATG---EEHGLDADVVVYATGYRPADGLGPLGAVADRCH
tr|A0A0F4QHH1|A0A0F4QHH1_9GAMM      TSVNAARINTEGKVVLELENIH-----GVSQVEYDQLVLATGYQYPSRSPLLEQVSEWLQ
tr|C1DIQ9|C1DIQ9_AZOVD              RTVEKVL-ANEGHIALTLRNIASG---EIETCDYDALILATGYERREHRQLLASIEEY--
tr|A0A375CHW0|A0A375CHW0_9BURK      KAVQSAQ-CGAGGIELAIGATAPGAPADTDTRRYDAVVLATGYERESHRRLLAPLARY--
tr|Q0K0K9|Q0K0K9_CUPNH              SEARHAE-ADADGVRLDIARRDDG---AHQLQRYDAVILATGYRRELHQSLLAPLASYL-
tr|Q0VMR1|Q0VMR1_ALCBS              RDIVGVQ-NDGTRVLLTLRNKDTG---VEQTEVYDGVVLATGYNRNGHEQLLSPMAHW--
tr|A0A0C4WTD7|A0A0C4WTD7_9GAMM      RQIQAVA-ASAGGMRLSLRDSQDG---SDELHEFDLLVLATGYRRDAHWSLLEGIERHLQ
tr|B2JPG8|B2JPG8_PARP8              ESVREVQAVNGSEVEMLVRDRMRD---EAALECFDAVVLATGYRRDAHHSLLEPLADALG
tr|N6W943|N6W943_9ALTE              REVARVE-TGEGGLHLTLRDLADD---SHSEQGFDAVVLATGYRRDQHHELLAGLGDH--
                                                     :                * :: ***:        *  :     

tr|Q0S7I4|Q0S7I4_RHOJR              PPRE----VGRDYRLAVSPDVTAGIYLQGG-TEKTHGITSSLLSNVAVRAGEIVTSVVTR
fuscachelin                         FDAAGRPSLQRDYRIVTDDTVTCGLYLQGG-TEHTHGISSVLLSNVATRAAEIIDSIEAR
scabichelin                         RDEEDALQVGRDHRVATAPDVSADIYLQGG-TEHTHGLTSTLLSTTAVRAGEICASLLAR
gobichelin                          ADDRGRLRVDRDHRVLMADHVDVGVYLQGG-TEHTHGITSSLLSTLAVRSGEICDSLLLR
qinichelin                          TDEQGRLRIDRDHRVMTTGRIRAGIYLQGGSTEHTHGITSTLLSTLAVRSGEICESLVRG
amychelin                           RDEHGRLRVERDYRL-VAPDLPGAIYVQGG-TEHTHGITSSLLSNTAVRVGEILASILDR
albachelin                          RDDEGRLRVERDYRIVTEPPLDGGIYLQGG-TEHTHGITSSLLSNTAVRVGEILQSIVDR
erythrochelin                       RDDQGRYRVARDYRLMTGSAVRGGIYLQGG-TEHTHGITSSLLSNTAVRGGEILRSIVDD
coelichelin                         RDDEGRVRVERDYRVTTDPALRCGIYLQGG-TEHTHGITSSLLSNTAVRVGEILESLLDR
salinichelin                        RDDQGRVRVERDYRVATDPELRCGIYLQGD-TEHTHGITSSLLSNTAIRVGEILESILDR
tr|A0A0F4QHH1|A0A0F4QHH1_9GAMM      PN------ITRQYQLETSEQFKPKIFTQGV-NEQTHGISDSLLSILAVRSAEIVDALEL-
tr|C1DIQ9|C1DIQ9_AZOVD              ---LDGYRVGRDYRLVTHETFKPAVFMQGV-CESSHGLSDTLLSVLPVRAEEIACSLHNA
tr|A0A375CHW0|A0A375CHW0_9BURK      ---LGDFSVDRNYRVQAAPELAVPVYLQGF-CQSSHGLSDTLLSVLPARAEEIAGDIHDA
tr|Q0K0K9|Q0K0K9_CUPNH              -DDAKGFQADRDYRLQMAPGCQAGVFLQGC-CEATHGLSDTLLSVLAVRAQEIAAAVLGN
tr|Q0VMR1|Q0VMR1_ALCBS              ---MSEQGVERCYRLPMAKGCHANVFLQGC-CEQTHGLSDTLLSILAVRSQEVVDALIER
tr|A0A0C4WTD7|A0A0C4WTD7_9GAMM      KEAE----LERSYRLPTRAGFQPNIFLQGC-CEDSHGLSDTLLSVVAVRSQEVADALLAA
tr|B2JPG8|B2JPG8_PARP8              KP-VGQCEVARDYLLATPAHFQPRIYLQGC-CEDSHGLSDTLLSVLARRADEIAGSLEAC
tr|N6W943|N6W943_9ALTE              ---LESFTPDRNYRLRLRNS-ESRIYLQGC-CEVSHGLSDTLLSVLAVRSQEILESIFLG
                                              * : :         :: **   : :**::. ***  . *  *:   :   

tr|Q0S7I4|Q0S7I4_RHOJR              RGRNGT----LASVNAQDTYATSEAR---------
fuscachelin                         RATS-------------------------------
scabichelin                         RAADLA----------------PAEA---------
gobichelin                          RTAEAL--------RADRDKEIDALLG--------
qinichelin                          VPAGAL-AGAGAGVLADGGARADGASADELAVQVG
amychelin                           RPSTEW----------DPEYAVKELA---------
albachelin                          RVADAS--------RPEYAVSGTGPA---------
erythrochelin                       RGTGMP--------------RLRVAQ---------
coelichelin                         GLESAS-----DEVRTVADGTGTGAR---------
salinichelin                        DLKVMP----------DAAPSVAAAR---------
tr|A0A0F4QHH1|A0A0F4QHH1_9GAMM      -----------------------------------
tr|C1DIQ9|C1DIQ9_AZOVD              VGKHNQTVQRSIRPLKALGGLLESAS---------
tr|A0A375CHW0|A0A375CHW0_9BURK      LAGERR---WMAQPAQAGGTQAIAAA---------
tr|Q0K0K9|Q0K0K9_CUPNH              RAGAACAMEAEPPRSRPARVAHAGTH---------
tr|Q0VMR1|Q0VMR1_ALCBS              QSRPIA---------------TACAS---------
tr|A0A0C4WTD7|A0A0C4WTD7_9GAMM      CSQLQV-----------------ACA---------
tr|B2JPG8|B2JPG8_PARP8              KNGNGV---AVQARTAQSGDRVAFAL---------
tr|N6W943|N6W943_9ALTE              RSVEPQ-------VRTERETRLTSAL---------
                                                                       
