CLUSTAL multiple sequence alignment by MUSCLE (3.8)


tr|C1DIP3|C1DIP3_AZOVD      ------------------------------------------------------------
tr|B3PGL4|B3PGL4_CELJU      -------------MTFSRRKFLASLTAAG-LVIP---GVYYAQREIRNRLINNDKDVTAG
tr|Q9I188|Q9I188_PSEAE      -------------MTVSRRGFMAGLALTGAAALP---VAYYTHRHLTR----EEEPQTPD
tr|Q1I7I7|Q1I7I7_PSEE4      -------------MTISRRGFIAGLAVAG-ATGT---AAYYAHKKLTHD--PEDDIVTPG
tr|Q88F86|Q88F86_PSEPK      -------------MTISRRGFIAGVALAG-VTVP---GALYVQRQLTR----EEFPETPG
tr|B0KNZ5|B0KNZ5_PSEPG      -------------MTISRRGFIAGVALTG-VVVPGALGALYVQRQREE---AEAFPETPG
tr|Q48KB4|Q48KB4_PSE14      MDNGCLGAGTGRVMTISRRGFIAGLALTG-AAVP---AAYYAHREFTR----VEEPVTPG
tr|G8Q461|G8Q461_PSEF3      ---------------------MAGLALTG-AAVP---AVYYGHRELTR----PDPTITPG
tr|K9NFD9|K9NFD9_9PSED      -------------MTISRRWFLAGLALTG-AAVP---AVYYGHRELTK----PDPAITPD
                                                                                        

tr|C1DIP3|C1DIP3_AZOVD      -------MLQDALLANRLVGVWDMRFIAGRQDFPEIPAGELQLLLDIGPGGRALRGYLGA
tr|B3PGL4|B3PGL4_CELJU      EAVAEPASHQGDLLAEKLRGIWDFQLLD-NGKLDALPHDKLEMILDVGVTGRALRGYLGT
tr|Q9I188|Q9I188_PSEAE      EASLDLAATDGIRLGDRLRGLWDLRLVGGDAELPGLPREGLQLVLDVAPKGRGLIGYLDT
tr|Q1I7I7|Q1I7I7_PSEE4      EASVELADYSGQVLADRLRGVWDLRLEGVDAGIEGLPAKGLEVFFDVATKGRGLRGYIDT
tr|Q88F86|Q88F86_PSEPK      EAVVELADTATQQLGDTLRGIWRWSFKGAQAGLPGLQGETLELFIDVAQKGRSIRGYLDT
tr|B0KNZ5|B0KNZ5_PSEPG      EAVVELADTPLQQLGDSLRGIWRWTLQGKDAGLDGLPAGELELFLDVAASGRALRGYLDT
tr|Q48KB4|Q48KB4_PSE14      EATAGPADTSTQRLADKLRGVWTLRFEGRDAGLADAPLEGLEMFLDIAPRGRGLRGYIDT
tr|G8Q461|G8Q461_PSEF3      EASFDVADVEGQRRADTLRGIWTIRFTGRDAGLEGLPQDDLQLFLDIGQRGRGLVGYLDS
tr|K9NFD9|K9NFD9_9PSED      EASFDVADVAGQRLADALRGVWQIRFEGRDAGLEGLPLEGLEVFLDIAHKGRGVVGFLDT
                                          .: * *:*   :      :       *::.:*:.  **.: *::.:

tr|C1DIP3|C1DIP3_AZOVD      PPYAGDI----LQVFGRLSGDKAPFLNLRMLDN--------QGRSLECRAIFDEIWGAWS
tr|B3PGL4|B3PGL4_CELJU      AISLRDKNEPEYRVLGSLATLSAPRVRWILCDE--------HGPRYECDAVMDEIWDSWG
tr|Q9I188|Q9I188_PSEAE      PERLLAAEPPRFRVLGDLLGASSASIRWRLVDQASG----SVAPTHDCSAVFDEVWADYA
tr|Q1I7I7|Q1I7I7_PSEE4      GERLRGDGEPAYRVLGDLVGASSREVRWRLVDT-------RGRSVYECVASLDEVWGRFA
tr|Q88F86|Q88F86_PSEPK      AERLRSGAEPRYRVLGDLPADKPGRLRWRLFDSADG----GRMPRYECHLVLDEVWGVFG
tr|B0KNZ5|B0KNZ5_PSEPG      PERLRGAEEPRYRVVGDLLADKPGTLRWRLFST---------QAHYECDIVLDEVWGRFG
tr|Q48KB4|Q48KB4_PSE14      PEQLRSDAQPRFRVIGDLQPANAAKLYLRVMDGHAGNDPHSDTADYEFSLTLDEVWGAFG
tr|G8Q461|G8Q461_PSEF3      AERLRDIDEPRYRVLGDLAGTDPKQLSWRLMSAR------QDAPDYECIMTLDEVWAGFG
tr|K9NFD9|K9NFD9_9PSED      AERLRSTEEPRYRVLGDLSGANPKQLGWRLLGA-------SGCCDYEFEMTLDEVWAGFG
                                        .*.* *   ..  :   : .              :    :**:*  :.

tr|C1DIP3|C1DIP3_AZOVD      TGGGKATLSGRLHRSGVQAGLSTQEASFVAVRRPFTASRERLSYVPELKAWLVSPGHRLF
tr|B3PGL4|B3PGL4_CELJU      N-AGAGTLSGNLRDLGYSLQLPEQKKRFVAHKRLFPEARERKPLNAELLAWLSSVEHRLF
tr|Q9I188|Q9I188_PSEAE      N-AGDGTLSGRIQRLERSPLSPNEDFRFVAVKRHFPLAHERIVLNEKLLGWLVSPQHRLF
tr|Q1I7I7|Q1I7I7_PSEE4      N-AGTGTLSGRLQRLDRPLTMPLLDNRFVAVKRLFPEARERLPYTPQMQAWVIGAEHRLF
tr|Q88F86|Q88F86_PSEPK      N-AGPATLNGSILDLERPLAMPEQDNRFLAHKQTFPEARERTALSPAMIDWLIAPEHRLF
tr|B0KNZ5|B0KNZ5_PSEPG      N-AGPATLHGRIARMDRALTLPVEDNHFLALKRTFPEARERTPLNPQLLAWLIAPEHRLF
tr|Q48KB4|Q48KB4_PSE14      N-AGSGTLSGRIERLDRPLALPELENRLIAIKQVFPEARERVGLSPPFLAWLVSKEHRLF
tr|G8Q461|G8Q461_PSEF3      N-AGSATLSGRVLRLDRPMALPEQDNHFIALKQRFPEARERTPLSPPLLAWLVSPEHRLF
tr|K9NFD9|K9NFD9_9PSED      N-AGSGSLSGRVLDLKRPLMLTAQDHRFIAVKQVFPEARERTGLNPALLAWLVSPEHRLF
                            . .* .:* * :         .  .  ::* .. *. :.**      :  *: .  ****

tr|C1DIP3|C1DIP3_AZOVD      HQVWHACRDRWHRLESTQRQGLRALGWQAGPLGKERDARGKHRHRNGSGEDFLFMHRDML
tr|B3PGL4|B3PGL4_CELJU      HQIWHASRDKWHQLSEKKREALRGLGWQPGPIGRERDARGRAKHRNGSGEDFLFMHRGMM
tr|Q9I188|Q9I188_PSEAE      HQLWHASRDKWHRLSEKQRNALRGVGWQPGPLDRERDARGPRKDRNASGIDFFFMHRHML
tr|Q1I7I7|Q1I7I7_PSEE4      HQLWHATRDKWHRLSAQKQNALRGLGWQPGPRDRERDARGPRKHRNGSGIDFLFMHRHML
tr|Q88F86|Q88F86_PSEPK      HQLWHASRDKWHKLDKDKRNALRGLGWQPGPRDRERDARGRHKDRNGSGEDFLFMHRHML
tr|B0KNZ5|B0KNZ5_PSEPG      HQLWHSSRDKWHKLDKSKQGALRGLGWQPGPRDRERDARGRHKDRNGSGEDFFFMHRHML
tr|Q48KB4|Q48KB4_PSE14      HQLWHASRDKWHKLPEDKRNALRGIGWQPGPREKERDARGPHKDRNGSGEDFFYMHRHML
tr|G8Q461|G8Q461_PSEF3      HQLWHATRDKWHTLDEDKRNALRGIGWQPGPRDEERDARGPRKDRNGSGVDFFFMHRHML
tr|K9NFD9|K9NFD9_9PSED      HQLWHASRDKWHKLSEDQRGALRGLGWQPGPRDRERDGRGVRKDRNGSGVDFFFMHRHML
                            **:**: **.** *   :. .**.:***.**   ***.**  . **.** **::*** *:

tr|C1DIP3|C1DIP3_AZOVD      IRARAMQ-DLRSWTSLPPPRPYIGHGIQAFVDYMANLDGFSVPPAWEVQGDESFNRWLYY
tr|B3PGL4|B3PGL4_CELJU      QRARELQPDLVCWSRLPLPAPFIEYDRQGFIRYYENVDGCSVPPAWEPTEDEEYSQWLRS
tr|Q9I188|Q9I188_PSEAE      HTARSMQ-DLPSWERLPRPVVPLEYDRPGFIRYFDNPDGFSVPPAWVAVDDDEYSEWLHG
tr|Q1I7I7|Q1I7I7_PSEE4      MYARTLQ-DLPSWPRFPLPQPNVEFDRQGFARYHDNHDGYCVPPAWQAPGDDAYGQWVSA
tr|Q88F86|Q88F86_PSEPK      GAARAIQ-DLPSWPRFPLPQPELERDRLGFARYFDNHDGNALPPTWLAYDDDEYTQWVRD
tr|B0KNZ5|B0KNZ5_PSEPG      GSARALQ-DLPSWSRFPLPQPELERDRAGFARYFDNHDGNALPPTWLASGDEEYTQWVRD
tr|Q48KB4|Q48KB4_PSE14      IQARKIQ-DLPSWPRFPLPQPELERDRLGFARYFDNHDGCSLPPNWLAQGDEEYTQLVSD
tr|G8Q461|G8Q461_PSEF3      GTARSFQ-PLPSWPRFPLPQPELERDRLGFARYLDNHDGTALPPTWLADGDAQYAQWVSD
tr|K9NFD9|K9NFD9_9PSED      GTARSMQ-DLPSWKHFPLPQPELARDRSGFARYFDNHDGTALPPTWLAEDDDEYSQWVSD
                              ** :*  * .*  :* *   :  .  .*  *  * ** .:** *    *  :   :  

tr|C1DIP3|C1DIP3_AZOVD      IKSSEGYYGDFQAWEAQYRDPEYLSTLCLGELGSRIELGIHDWLHMRWASIPRDPNSGLP
tr|B3PGL4|B3PGL4_CELJU      VKGSEAFYSNYQVWESLYHDPEYLSQMTLGEFGSELELGIHDWLHMRWATVTRDPSNGMP
tr|Q9I188|Q9I188_PSEAE      LKSAEAYHANFLVWESQYQDPAYLAKLTLGQFGSELELGMHDWLHMRWASVTRDPSNGAP
tr|Q1I7I7|Q1I7I7_PSEE4      IKANETFCGNFQVWESQYQDPVYLSKLSLGAFGSELEMTLHDWLHMCWASVPRDPNNAAP
tr|Q88F86|Q88F86_PSEPK      IKSAETFHGNFEVWESRYSDPQYLSRLTLGQFGSELELGLHDWLHMRWASVPRDPSNGMP
tr|B0KNZ5|B0KNZ5_PSEPG      IKTPDTFHGNFQVWESRYTDPQYLSTLTLGQFGSEVELGLHDWLHMRWASVPRDPSNGMP
tr|Q48KB4|Q48KB4_PSE14      IKSHETFHTHFQVWESQYRDPRFLSKLTLGQFGSQVELELHDWLHMRWASVARDPANGQP
tr|G8Q461|G8Q461_PSEF3      IKTAETYHSNFQVWESRYRDPRYLSKLTLGQFGSEVELGLHDWLHMRWASVPRDPSNGHP
tr|K9NFD9|K9NFD9_9PSED      IKTGETYHSNFQVWESRYRDPRYLSTLTLGQFGSEVELGLHDWLHMRWASVPRDPSNGQP
                            :*  : :   : .**: * ** :*: : ** :** :*: :****** **::.*** .. *

tr|C1DIP3|C1DIP3_AZOVD      MPFGRGSADFAEHWYRPGNDYLGDPFSSHVDPVFWSFHGWIDDRIEDWFLAHEQTHPGQV
tr|B3PGL4|B3PGL4_CELJU      LFWDRRYTDFSPRWFLPENDYLGDPFSSHVNPVFWMFHGWIDDRVEDWFRAHERIHPGEV
tr|Q9I188|Q9I188_PSEAE      VMTDRFPADFAPRWFRPENDFLGDPFSSHVNPVFWSFHGWIDDRIEDWYRAHERFHPGEV
tr|Q1I7I7|Q1I7I7_PSEE4      VPFARDQADFAARWFERENDFLGDPFSSHVNPVFWGFHGWIDDRIDDWFRAHERFHPGQV
tr|Q88F86|Q88F86_PSEPK      VPMARTPDDFAARWYGAQNDFLGDPFSSHVNPVFWRFHGWIDDRVEDWFRAHERFHPGAV
tr|B0KNZ5|B0KNZ5_PSEPG      VPTARTPDDFAERWFTADNDFLGDPFSSHVNPVFWHFHGWIDDRIEDWFRAHERLHPGEV
tr|Q48KB4|Q48KB4_PSE14      VPMARRSDDFAERWFEPENDFLADPFSSHVNPVFWMFHGWIDDRIDDWFRAHERFHPGEV
tr|G8Q461|G8Q461_PSEF3      VPFARDPDDFAARWYAPENDFLGDPFSSHVSPVFWAFHGWIDDRLEDWFRAHERFHPGEV
tr|K9NFD9|K9NFD9_9PSED      VPFARDPADFSARWFAAENDFLGDPFSSHVNPVFWHFHGWIDDRLEDWFRAHERFHPGQV
                            :   *   **: .*:   **:*.*******.**** ********::**: ***. *** *

tr|C1DIP3|C1DIP3_AZOVD      VRKTIDGVPWFAPGPWVRVAEPWLGPARAGCGAWGRSNRGDGGELDMETMKLALRIVFAD
tr|B3PGL4|B3PGL4_CELJU      ERKTIKGVSWFAPGRWVQIADPWLGASSYGC--IPSKNRRDRVALNKEEMKLALRIALSG
tr|Q9I188|Q9I188_PSEAE      QRREVEGIQWFAPGRWVEVGDPWLGPATHGCGLSDVQASSNSVELDVETMKLALRIIFSE
tr|Q1I7I7|Q1I7I7_PSEE4      RRQDVNGVPWFAPGHWVEVDDPWLGPDTHGCSTQPGTRPGKSVEMDVETMKLALRITFGE
tr|Q88F86|Q88F86_PSEPK      VRQEVNGVPWFAPGRWVEVADPWLGPDTHGCSNVAGLRPGRSVEMDPETMKLALRLIYSD
tr|B0KNZ5|B0KNZ5_PSEPG      RRLEVNGVPWFAPGRWVEVADPWLGPDTHGCSTVPGLRPGRSVEMDPETMKLALRIIYSD
tr|Q48KB4|Q48KB4_PSE14      KRLEVNGVPWFAAGRWVEVSDPWLGPETHGCSTVPGQAAGTTMEMDPEVMKLALRITFAA
tr|G8Q461|G8Q461_PSEF3      SRLDVNGVPWYAPGRWVEIADPWLGPDTHGCSTTPGLQVGRSVEMDPETMKLALRITFGS
tr|K9NFD9|K9NFD9_9PSED      SRLQVNGVPWFAPGRWVEIDDPWLGPVTHGCSTTPGLQAGKSVEMDPETMKLALRITFGE
                             *  :.*: *:*.* ** : :****.   **             :: * ******:  . 

tr|C1DIP3|C1DIP3_AZOVD      EE-EAERLEDRVPRRPWYGRHLTRGDPHD--
tr|B3PGL4|B3PGL4_CELJU      ET-DVPDLLRRIARRPWYARNLKLEK-----
tr|Q9I188|Q9I188_PSEAE      ED-QLSGWLKRAPRRPWYARNLKLARDQLRR
tr|Q1I7I7|Q1I7I7_PSEE4      DD-KIDGFLRKVPQRPWYARHLSMKNILS--
tr|Q88F86|Q88F86_PSEPK      EE-RFDGLVGKVPRRPWYARHLKVRQRS---
tr|B0KNZ5|B0KNZ5_PSEPG      ED-LFDKLRPKVPQRPWYARNLKVAKRSG--
tr|Q48KB4|Q48KB4_PSE14      DD-KLSNLLRRVPRRPWYARNLLPDRWF---
tr|G8Q461|G8Q461_PSEF3      DDKKLSELFRRVPQRPWYARNLKSKPV----
tr|K9NFD9|K9NFD9_9PSED      DEKKLKDLFRKVPQRPWYARNLKAKQSQA--
                            :         . ..****.*:*         
