CLUSTAL multiple sequence alignment by MUSCLE (3.8)


BAB74335.1                       ----MLKLTPQEIWQGFHWSFFINIQGLIICLHRFNLELIDGNLQQAQIELKTATKLMLA
AFZ60768.1                       --MIDIKNEPQQIWEGFHWSFFINTQGLIICLSRFEMNLALGNIPEAQIELETAAELMMA
WP_104904853.1                   MTKIETQVKLKQLWEGFHWLFFVDVQGLIICLRRFEIELAAGNLCQAEVELGTATKLMLA
QCO55742.1                       ----MTPPHAREIWREFHWAFFLHTQGMILCLRRFAGCLECNDLKGAETELETATTLMDA
FbnM_tr|Q7CT24|Q7CT24_AGRFC      --MTIALPSPSRIWREFHWAFFMNVQGLVLCLRRFNMQVHEGNFAEANRELRAAAVLLRT
L_ACM39978.1                     -MIALSPPSPYAIWREFHWAFFLNVQGLIVSLRRFQLSVERGQLTSAEQELNTASTLLVS
                                             :*  *** **:  **:::.* **   :  .::  *: ** :*: *: :

BAB74335.1                       SGASMELAGSLSPELYEAEIRPSMMPPHVKSHDFSGLMSWEHSVLIKVWKQLRPHFANLP
AFZ60768.1                       SGAAMELAGSFSRKEYENQVRPTMAPPYVQSNDFSGLMSWEHSWLVKIWKRLRPVFERLP
WP_104904853.1                   SGAAMELAGSFSRKEYENQIIPTMKPPQVESENFSGLMSWDHALLIKILKRLSPVFQALP
QCO55742.1                       SAAAMQLAGSFTRAEYERDIRISMTPPNVKSEGFSGLMSWEHGALVNLWRSLRPHFANLP
FbnM_tr|Q7CT24|Q7CT24_AGRFC      SASSMDLAASFSKADYENTIRVSMTPPSVESDDFSGLMSFDHAVLIQVWREMKDVFATLP
L_ACM39978.1                     SAASMELAASFPKDVYEATVRTSMTQPHVESDDFSGLMSWDHAVLISVWRDLRPIFETLP
                                 *.::*:**.*:.   **  :  :*  * *:* .******::*. *:.: . :   *  **

BAB74335.1                       TELKAEHQGFVDAYLYLAKSHRAVCQKFGGEEAGSLRFERSCAVDVLDAFARSRCQFINP
AFZ60768.1                       ADLEPQHHKLVAAYFSLAKSHKAVCEKFGGGEVGSLRCDNSTAVDVLDRFSQNRWRLIDP
WP_104904853.1                   VELHTQHSQFVNAYVTLSSAHTAVCTRFGGDEKGSLRCNKSTAVSKLKIFAQNRLKLIDP
QCO55742.1                       VALQPAHAEFAAAYRRMADGHVKVCARFVGEDAISLRYGDRDALASLRRFGKSRHALINP
FbnM_tr|Q7CT24|Q7CT24_AGRFC      VELHDAHAEFVAAYKYLAEGHVGVCSRFVGSDAGSLRYGDRKAIDTLQRFERGRLGMIDP
L_ACM39978.1                     DELASAHSAFIAAYKYLAESHTGVCSRFV--DSGSLRFEDRNAVDTLRRFERGRLGLIDP
                                   *   *  :  **  ::..*  ** .*   :  ***     *:  *  * ..*  :*:*

BAB74335.1                       EN--LEKCVTQRRRSAE
AFZ60768.1                       NFKVSAGCPFHQHEKAN
WP_104904853.1                   NHKVTDG----------
QCO55742.1                       EAE-PEGTDA-------
FbnM_tr|Q7CT24|Q7CT24_AGRFC      P---KKGCPFHK-----
L_ACM39978.1                     K---GKGCPFHS-----
                                                  
