CLUSTAL multiple sequence alignment by MUSCLE (3.8)


L_WP_104904852.1                 ------------MTHNSLPSQL------YLLVPWNLPIEQQLSESDQVKTRQVLKNLLQA
L_BAB74336.1                     -------------------MLL------ELLNPAELPIQQQLTPPTQIKLKKILTELLTA
L_AFZ60769.1                     ------------MTKNHFSVQL------HLLVPWDLPIEQELNEVDKTKLYEALTQLLLA
L_QCO55743.1                     MTVVQAIAAEDSIAADQGSGAL------HLLLPTNLPTEITLTPEDRVAMRDAVTRFLTV
FbnL_tr|A9CFJ0|A9CFJ0_AGRFC      MDDQPWPSPAPRADAGPDRDWLAQDAVLDLLLPEALAPVMAPEEHDKARLQYILCEALEA
M_ACM39979.1                     ------------MEAPADDGWL------DLPLPDGLPAETPLSEIEKRRMHGVLSGLLEA
                                                      *       *  *  *.         .      :   * .

L_WP_104904852.1                 LDELSHRKALAIINQELANLDVSNISPASISSTETSLEPWEVEDFNRCFKATYVTTKESS
L_BAB74336.1                     LNKPDIQQAINNIETAIAELEIYDVFPLETISTQTTLKYWEIEDFDTYFHVQHVQSNEPE
L_AFZ60769.1                     LKKPGVQEALITVNQALTNLEITDVITAEISSTETSLKTVEVEDFDNYFGVMHIQTQEPA
L_QCO55743.1                     LQSQDPAAGIAEILQGLATGKPYKAVP--VGSVGIPAQVSEVEDFDAYFNVRRIAPEHPA
FbnL_tr|A9CFJ0|A9CFJ0_AGRFC      F-TLHYPECRARIAALLGNMEKPMSDPGIVDVSGLPLTSFHANDYDRYFRVNRITTAEPA
M_ACM39979.1                     I-KLDHPQSTAQLDALLTDLGKAAGERPEIETAGLPLTPFQATDYDRYFRVNRQSAEEPA
                                 :           :   :                  .       *::  * .    .  . 

L_WP_104904852.1                 VCIVWGLLIVYKTLLILDEDGKKFDPDRVKDLKEGLKSYVYLLGRVFSLSLEEI-
L_BAB74336.1                     LCLVKGLLSACQTFLYLQQDNLNLDITQIELQREGFKNYVYLLDRVFQLNLESC-
L_AFZ60769.1                     SCLVRSLLLAYRNFLELSQNFDDFDPIHIEMQKKGFETYTYLLSRVFSLCLEKIS
L_QCO55743.1                     HALLVGLLQTSAAAFALAARDTRMPRDLLGHQAKGFAAYARLLGRICG--IDGLS
FbnL_tr|A9CFJ0|A9CFJ0_AGRFC      HVLLRSFLQVALSVTDLFCRAPHLSEKAAKAQFDGFEVHARLLARCFG--VECAR
M_ACM39979.1                     VAMVRSLIQTVRAVTQLFARSPELPVVHVRHQMEGFESHAHLLARTFG--LEPLR
                                   :: .:: .      *      :         .*:  :. ** *     ::   
