CLUSTAL multiple sequence alignment by MUSCLE (3.8)


WP_084025528.1      -----------MHPESLDAAAREDAPRNGSWRERIILGDECPPRAV-PEWLAASYETLRG
WP_150685442.1      --MQLDPRDVLDSPRSTESSPAPRRATASDWRSRVILGEQVGDVVL-PDWLETSYETLRT
MegE                MRNRWLRTREMTMESSNVGVTNFDGFVAEDWKSRIIDGRATGAAVTLPAWLDASYETLRE
WP_042628142.1      --MRSTEDKVNVMPQPGVATPGSEGFDPGDWKSRVIAGRALGAAANPPAWLDASYETLRK
WP_085229610.1      --MEAGNGGMFGEPSGGSAKGRP--FVADNWRSRVIEGHATGPAASIPEWLAASYATLRT
WP_114156049.1      ------------MQAGNSAVGEADRFEVSDWKSRIIAGKATGAAVSAPAWLDASYATLRE
                                      .          .*..*:* *      .  * ** :** *** 

WP_084025528.1      KVMDPAYPCFFGTQAEKRGEMFYSYVTGRDWSMLPATMRTFASLSALPQYQKNNIAIFFE
WP_150685442.1      QVMHPEYPCFFGTIAERRGEMFYTFVNGKDNAMLPATMLTFARLASQPEFRRNNIAIFYE
MegE                QVMHPEYPCFFGTMAEKRGEMFYAFVNGKDIGTLPATMQTFAELASLPQYRKNNIAVFFE
WP_042628142.1      QVMHPDYPCFFGTMAEKRGEMFYAYVNGKDISQLPATMQTFAELALRPEYRKNNIAVFFE
WP_085229610.1      HVLDPAYPCFFGTMAERRGEMFYSFVNGKDTRGLPATMQTFAALASQPQYRRNNLAVFFE
WP_114156049.1      QVLDPAYPCFFGTMAERRGEMFYSFVNGRDLRDLPATMQTFAELAVRPEYRRNNIAVFFE
                    :*: * ******* **.******::*.*.*   ***** *** *:  *::..**:*:*:*

WP_084025528.1      PDREPRGHDAYREDFWRILQGLHDVDPDPAADGQPDPDHADWEFSFAGVQMFVVCACPSF
WP_150685442.1      PDTTPLTHNEYHDLFWGTLQYLHNVDPDPEADQQVPPSHEDWEFGYGGLQMFVVCACPSF
MegE                PDAQPLTHDTYHDLFWNILQTLHNVDPDPSAADQPEPSHEDWEFSFAGVQMFVVCACPSF
WP_042628142.1      PDPQPLTHEAYQQHFWQILQHLHDVDPDPKADAQPDPSDGDWEFSFAGVETFVVCACPSF
WP_085229610.1      PDAVPLAHDEYRAFFWRILQQLHDVDPDPQADEQPEPSDEAWEFSYSGVQMFVVCACPSF
WP_114156049.1      PDPEPLSHDAYRTLFWGILQRLHDIDPDPAADQQPDPMDEAWEFSYAGVQMFVVCACPSF
                    **  *  *: *.  **  ** **::**** *  *  *    ***.:.*:: *********

WP_084025528.1      RVRRSRNLGPGMVLLFQPRSVFIDKVTNRVIGVQARTEVRRRLERWDDIGAHPDLGFYGD
WP_150685442.1      SQRHSRNLGPGMVLLFQPRAVFVDTITNKVIGRQAREQVRERLRKWDAVGPHPDLGFYGD
MegE                NERHSRNLGPGMVLLFQPRSVFVDTITNKVIGREARNQVRKRLETWDDVSAHPDLGFYGD
WP_042628142.1      RSRHSRNLGPGMVLLFQPRSVFVDTITNKVIGREARNQVRKRLETWDEVAAHPDLGFYGD
WP_085229610.1      RARHSRNLGPGMVLLFQPRSVFVDTITNKVIGREARIEVRKRLDTWDDIPAHPDLGFYGD
WP_114156049.1      RARHSRNLGPGMVLLFQPRSVFVDTITNKVIGREARNQVRKRLETWDDIPAHPDLGFYGD
                      *.***************:**:*.:**.*** :** :** **  ** : .*********

WP_084025528.1      PANREWKQYFLPDDNSAAS-RCPFLNRRH-
WP_150685442.1      PGNLEWKQYFLEDENVAAADQCPFLKRM--
MegE                PGNLEWKQYFLSDDNTAAADRCPFLRRQKD
WP_042628142.1      PGNLEWKQYFLDDANLPADDRCPFLKR---
WP_085229610.1      PGNLEWKQYFLDDANMPAGDRCPFLKRKGR
WP_114156049.1      PGNLEWKQYFLDDANAPIEERCPFLKR---
                    *.* ******* * * .   .****.*   
