CLUSTAL multiple sequence alignment by MUSCLE (3.8)


sp|P9WKF7|MBTG_MYCTU        MNPTLAVLGAGAKAVAVAAKASVLRDMGVDVPDVIAVERIGVGANWQASGGWTDGAHRLG
sp|P9WKF7|MBTG_MYCTU        MNPTLAVLGAGAKAVAVAAKASVLRDMGVDVPDVIAVERIGVGANWQASGGWTDGAHRLG
tr|D5UZ39|D5UZ39_TSUPD      -MTDLLIVGAGPKAVAVAAKAAVLRANGLPAPSITVVDPLGVAGNWRAAGGWTDGAHRLG
tr|W5T955|W5T955_9NOCA      -MKTLLVVGAGPKAMAVAAKARVLRDLGLPAPRVVVVESHAVGGNWLPSGGWTDGQHRLG
Lys_nocobactin              -METLLVVGAGPKALAVAAKSHVLRQLGLSAPRVIAVEAHAVGGNWLASGGWTDGRHRLG
                                * ::***.**:*****: ***  *: .* : .*:  .*..** .:****** ****

sp|P9WKF7|MBTG_MYCTU        TSPEKDVGFPYRSALVPRR----NAELDERMTRYSWQSYLIATASFAEWIDRGRPAPTHR
sp|P9WKF7|MBTG_MYCTU        TSPEKDVGFPYRSALVPRR----NAELDERMTRYSWQSYLIATASFAEWIDRGRPAPTHR
tr|D5UZ39|D5UZ39_TSUPD      TSPLKDVGYPYRSRIAGGGGGAVDAEVDRGMLLLSWTAHLTDRGAYADWVDRGGPAPTHT
tr|W5T955|W5T955_9NOCA      TSPEKDVGFPYHSTWARGH----NRDIDREMVAYSWNSFLVENGTYAEWVDRGRPSPHHH
Lys_nocobactin              TSPEKDIGFPYHSTWARGH----NREINEAMMAFSWTSFLVEHGTYAEWIDRGRPSPQHH
                            *** **:*:**.*  .       : :::  *   ** :.*   .::*:*:*** *:* * 

sp|P9WKF7|MBTG_MYCTU        RWSQYLAWVADHIGLKVIHGEVERLAV----TGDRWALCT-----HETTVQADALMITGP
sp|P9WKF7|MBTG_MYCTU        RWSQYLAWVADHIGLKVIHGEVERLAV----TGDRWALCT-----HETTVQADALMITGP
tr|D5UZ39|D5UZ39_TSUPD      EWAAYLAWVAERVGMEPVRDTVVALSP----DGDGWSVGLASGERRA----ATRVMITGP
tr|W5T955|W5T955_9NOCA      VWANYLQWVARKSGVEIVLGAVRRVRA----AADGWLVTVADAHGEETEIDTDGLMITGP
Lys_nocobactin              VWAKYLQWVARKIDLELVLGKVRTIRQRPTDGGAGWSVEVAGADGATTELEADGLMITGP
                             *: ** *** . .:: : . *  :       .  * :             :  :*****

sp|P9WKF7|MBTG_MYCTU        GQAEKSLLPGNPRVLSIAQFWDRAAGHDRINAERVAVIGGGETAASMLNELFRHRVSTIT
sp|P9WKF7|MBTG_MYCTU        GQAEKSLLPGNPRVLSIAQFWDRAAGHDRINAERVAVIGGGETAASMLNELFRHRVSTIT
tr|D5UZ39|D5UZ39_TSUPD      GSSGRALLV-DPAVLSVADFWAAAAARALPPGARVAVIGGGETAASALDELVRHDVFAIT
tr|W5T955|W5T955_9NOCA      GNSRRALAQ-HPKVLSIADFWDLAGKRRLPVSSRAAVIGGGETAGSAVDELVRHDVLTVS
Lys_nocobactin              GQSTKALAK-HPRVLSIAEFWDLAGKRKLPISSRAAVIGGGETAGSALDELVRHEMLTIS
                            *.: .:*    * ***:*:**  *. .    . *.*********.* ::**.** : :::

sp|P9WKF7|MBTG_MYCTU        VISPQVTLFTRGEGFFENSLFSDPTDWAALTFDERRDALARTDRGVFSATVQEALLADDR
sp|P9WKF7|MBTG_MYCTU        VISPQVTLFTRGEGFFENSLFSDPTDWAALTFDERRDALARTDRGVFSATVQEALLADDR
tr|D5UZ39|D5UZ39_TSUPD      VVSPTPTLFTRGESYFENALYSDPSRWAMLGEQERRDVIRRTDRGVFSARVQEALLAENR
tr|W5T955|W5T955_9NOCA      VISPGATIYTRGESYFENSLFSDPAKWRALSLQERRDVIRRTDRGVFSVRVQENVLADNR
Lys_nocobactin              VISPMATIYTRGESYFENSLFSDPTKWNALSIQERRDVIRRTDRGVFSVRVQESLLGDNR
                            *:**  *::****.:***:*:***: *  *  :****.: ********. *** :*.::*

sp|P9WKF7|MBTG_MYCTU        IHHLRGRVA--HAVGR----QGQIRLTLSTNRGSENFETVHGFDLVIDGSGADPLWFTSL
sp|P9WKF7|MBTG_MYCTU        IHHLRGRVA--HAVGR----QGQIRLTLSTNRGSENFETVHGFDLVIDGSGADPLWFTSL
tr|D5UZ39|D5UZ39_TSUPD      VHHVPGRVVGLRRVGPDGAAGGGIELCL----RATAPYTPPAYDLVVDATGGDPLWFRSL
tr|W5T955|W5T955_9NOCA      VHHLQGRVV--RVAER----GDGVSLTL---RNERRPDQVHAFDLVVDATGGQPLWFLDL
Lys_nocobactin              VHHLQGRVT--RIVGQ----GDGVAVTL---RNEMRADQVHNFDLVVDATGGQPLWFLDL
                            :**: ***.  . .       . : : *              :***:*.:*.:**** .*

sp|P9WKF7|MBTG_MYCTU        FSQHTLDLLELGLGGPLTADRLQEAIGYDLAVTDVTPKLFLPTLSGLTQGPGFPNLSCLG
sp|P9WKF7|MBTG_MYCTU        FSQHTLDLLELGLGGPLTADRLQEAIGYDLAVTDVTPKLFLPTLSGLTQGPGFPNLSCLG
tr|D5UZ39|D5UZ39_TSUPD      LDPAAQDLLESAVGGPVSTARVESAMGYDLAVSGVTQKLHLPTLAGFAQGPGFANLSCLG
tr|W5T955|W5T955_9NOCA      FDSDAADLVELAVGGPVTQGRLEAAMGHDLAVAGLDAKLYLPNLSGMAQGPGFPNLSCLG
Lys_nocobactin              FDSESADLLELAVGGPLTQQRIESSIGYDLAVTGLGAKLYLPNMAALAQGPGFPNLSCLG
                            :.  : **:* .:***::  *:: ::*:****:.:  **.**.::.::*****.******

sp|P9WKF7|MBTG_MYCTU        LLSDRVLG--AGIFTPTKHNDTRRSGEHQSFR---------
sp|P9WKF7|MBTG_MYCTU        LLSDRVLG--AGIFTPTKHNDTRRSGEHQSFR---------
tr|D5UZ39|D5UZ39_TSUPD      ELSDRVLGTVSGASSHGAAGAGRAAGGAVPGATVSRPVATG
tr|W5T955|W5T955_9NOCA      ELSDRILG---GVPAHAVMPAARAAGVAGPR----------
Lys_nocobactin              ELSDRVLR---AEPARVRAGARQLAAQ--------------
                             ****:*    .  :       . :.               
