CLUSTAL multiple sequence alignment by MUSCLE (3.8)


tr|G7LM40|G7LM40_9GAMM              --------------MLKPKDCRNLQDVREGIDTIDKQIFTLFLQRLDYVYSASRFKPDEA
tr|A0A3S0PAK1|A0A3S0PAK1_9VIBR      -MTIKLTSRDIGIDAETPDDCKSLGDVRQAIDTIDKQIIQLLGMRKGYVLSAAQFKETAE
tr|A0A418T7G6|A0A418T7G6_9RHOB      --MSRLTHDEPGLHPVLPDDARSLDDIREGIDGIDRRMIELLALRLDYVQRAADFKPDLA
WP_011749279.1                      MSPAVVAPEDLAPDLVPPEAVAGLGDVRRGIDMIDARIVGLLGLRLRYVLAAADFKPDIA
tr|A0A348HD66|A0A348HD66_9GAMM      --------------MQTPITCRSLTDIRQAIDRIDHDIILKLAERMHYVLAASYFKPDAA
tr|A0A0X1T668|A0A0X1T668_PSEAA      -----------MNAIKPALQCANLQDIRQGIDHLDRQLVELLAARLTYVQAATRFKANLQ
AAO56100.1                          -----------MNVVKSAPECENLGDIRQGIDELDRQIVQILARRLTYVKAATRFKASQQ
KJY78326.1                          -----------MSSLKKPEACESLNDIRVGIDTLDKEIVQILSKRMRYVKAAAQFKPDEE
WP_011081756.1                      -----------MASLKKPEACESLNDIRLGIDTLDKEIVHILSQRMGYVKAAAQFKPDEK
tr|G7ZCF9|G7ZCF9_AZOL4              --------------MKSPEQCADLQDVRTGIDTIDRQIVTLLGERLRYVHAAAAFKPTVE
AIB42180.1                          -----------MLPLKPPQACENLNDIRAGIDFFDRQILDSLQKRLRYVKAAAQFKANEQ
WP_011533710.1                      -----------MLQPKTPEACTSLTDIRAGIDFHDRQIFEALVKRLGYVKAAVQFKANEQ
ABJ13503.1                          --------------MKTPEDCTGLADIREAIDQIDLDIVQALGRRMDYVKAASRFKANEA
WP_041752761.1                      --------------MKTPEQCSGLDDVRCGIDAMDQQIIQALGLRLAYVKAAAQFKPTED
                                                     .    .* *:* .**  *  :.  :  *  **  *  **    

tr|G7LM40|G7LM40_9GAMM              SISAPERVESMLDERRRWAKEHHVDENFIASLYENIIHKFISAQIKFWRA----------
tr|A0A3S0PAK1|A0A3S0PAK1_9VIBR      AIPAPERVAAMLKARQCWSKEAELSEDFIVPLYAQIIQWFIQQQTHFWHK----------
tr|A0A418T7G6|A0A418T7G6_9RHOB      SVPAPERVRAMLDDRAEWAASLGLSSDFIAPLFAQVSEWFIRQQVAHWPD----------
WP_011749279.1                      SIPAPERVRQMLDERAAWAAEAGLAPDFIGPLFGQVAEWFIRQQVAHWRACRAGQSAADH
tr|A0A348HD66|A0A348HD66_9GAMM      SIPAPERVRAMLPKRMQWAEEHQLDGTFVHDLFTQLIQWYITQQTLYWHQ----------
tr|A0A0X1T668|A0A0X1T668_PSEAA      AIPAPERVSAMLEERRLWAADAGLPVDETEEFFGDLIHWFINLQINHWHT----------
AAO56100.1                          AIPAPDRVRAMLEERRQWANDAGLPVDETEDFFKDLIHWFINQQITHWRA----------
KJY78326.1                          SIPAPERVLVMLEDRKKWAIEAGISSEYVESLFSNIIEWYINQQIKHWRT----------
WP_011081756.1                      SIPAPERVASMLEERRHWANEQGLSEEYVEALFDNIIQWYISQQIQHWRS----------
tr|G7ZCF9|G7ZCF9_AZOL4              SIPAPERVAAMMVERRSWAVEVGLPPDFVAGLFAKITDWYIATQTAYWRA----------
AIB42180.1                          DIPAPERVAAMLEERRLWAVEAELDVAFVEKLYEQIIHWNIQQQILHWRA----------
WP_011533710.1                      AIPAPERVAAMLQDRLEWAASEGFDAQFIEQLYTLIIHWNIDQQIQHWRS----------
ABJ13503.1                          AIPAPERVAAMLPERARWAEENGLDAPFVEGLFAQIIHWYIAEQIKYWRQ----------
WP_041752761.1                      SIAAPERVAAMLPQRRQWAEQASLDPMFVVPLFAQIIHWNIAQQVRHWRR----------
                                     :.**:**  *:  *  *: .  .       ::  :  . *  *  .*            

tr|G7LM40|G7LM40_9GAMM              -----------SKSS----------------
tr|A0A3S0PAK1|A0A3S0PAK1_9VIBR      -------------------------------
tr|A0A418T7G6|A0A418T7G6_9RHOB      -----------RNPVTRESKSGTTSASGVDN
WP_011749279.1                      RRSSAPAPSPSARPPSEPALDRVERVHGAGD
tr|A0A348HD66|A0A348HD66_9GAMM      -----------QHPPSQNDSAL---------
tr|A0A0X1T668|A0A0X1T668_PSEAA      -----------LHLQEAQP------------
AAO56100.1                          -----------LHPEAQP-------------
KJY78326.1                          -----------IRGLSNEESENPVS------
WP_011081756.1                      -----------QKGLAPVSQD----------
tr|G7ZCF9|G7ZCF9_AZOL4              -----------RRDA----------------
AIB42180.1                          -----------TRQPTYSAQAKS--------
WP_011533710.1                      -----------IHGEKA--------------
ABJ13503.1                          -----------TRGAA---------------
WP_041752761.1                      -----------QHGLDQGAQDE---------
                                                                   
